# Generated by Django 5.0.3 on 2024-03-17 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='product/images/')),
                ('date', models.DateField(verbose_name=datetime.datetime(2024, 3, 17, 14, 6, 27, 16768))),
            ],
        ),
    ]
